name: Build and Deploy (branch deploy)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # - name: Install deps
      #   run: npm ci

      # - name: Build static export
      #   run: npm run build

      - name: Add .nojekyll
        run: |
          mkdir -p out
          touch out/.nojekyll

      - name: Copiar JSONs para pasta out
        run: |
          test -f home.json && cp home.json out/home.json || (echo "home.json não encontrado" && exit 1)
          test -f away.json && cp away.json out/away.json || (echo "away.json não encontrado" && exit 1)

      - name: Deploy to 'deploy' branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: out
          clean: true
